package enums

enum class ChatState {
    AUTHORIZATION,
    MAIN_MENU,
    FINDING_INTERLOCUTOR,
    TALKING,

    FILLING_FORM_MAIN_MENU,
    FILLING_FORM_DORMITORY,
    FILLING_FORM_FACULTY,
    FILLING_FORM_INTERESTS,
    FILLING_FORM_SEX,
}
